#!/bin/bash
set -eou pipefail

fail=0
casks=()
for caskfile in Casks/*.rb; do
  cask="$(basename -s .rb "$caskfile")"
  # Skip community edition casks
  if [[ "$cask" == *"-ce-"* ]]; then
    continue
  fi
  if ! grep "$cask" README.md >/dev/null; then
    echo "Cask $cask is not listed in README.md"
    fail=1
  fi
  casks+=("$cask")
done >&2

tmp_tap="dahlia/jetbrains-eap-$RANDOM"
brew tap "$tmp_tap" .
brew audit --git --cask --online "${casks[@]/#/$tmp_tap/}" || fail=1
brew untap "$tmp_tap"
brew style --casks Casks/*.rb || fail=1

if [[ "$fail" = "1" ]]; then
  exit 1
fi
